### ISSUE TITLE
Project name change request

### ISSUE THREAD

**Issue by iStrayMentis** [bounswe/bounswe2015group8#135]
I suggest changing our project name from "Lokum" to "Clash of Cultures".
@Xyllan @burak-tepedelen @tugceeskili @bugrahan @goktugerce @arslanbenzer @siray @sinanharputluoglu @berksalmanoglu @gokcantali

**Comment by Xyllan** [comment]
Proposing the name "WeStory" for the project. It is close to our purpose of sharing everyone's stories about cultural heritage and sounds like history.

**Comment by tugceeskili** [comment]
We have decided our project name to be "WeStory" as proposed. Congrats guys !
