### ISSUE TITLE
WeStory Logo

### ISSUE THREAD

**Issue by mrtysn** [bounswe/bounswe2015group8#194]
Create logo for the project

**Comment by iStrayMentis** [comment]
![apfc_xf-lmcpq93eemrdn8qxhc3olhsvsyvk_wn8j5dt](https://cloud.githubusercontent.com/assets/5190929/10902718/77a861ce-820a-11e5-87de-0a85326f9690.jpg)
Initial design

**Comment by bugrahan** [comment]
![logo](https://cloud.githubusercontent.com/assets/4963296/11483836/7a2bc18e-97b3-11e5-8bfb-86868ca889de.png)

**Comment by siray** [comment]
![logowestory](https://cloud.githubusercontent.com/assets/9386464/12073942/2fcd4c4a-b142-11e5-9659-4cba85baa88a.png)

Our logo has been created, thanks Mert :)
