### ISSUE TITLE
fix bugs for android

### ISSUE THREAD

**Issue by arslanbenzer** [bounswe/bounswe2015group8#225]
fix such bugs;
-log in crashes sometimes
-non-users can add heritages
-non users can see edit heritage, edit post buttons, but when tried, application crashes.
-when users wants to see heritage of a post, he/she sees and edit page.

**Comment by Xyllan** [comment]
Fixed bugs related to unauthorized members being allowed to edit or add things on android/design branch. Crashes regarding unexpected replies from server will be handled later.

**Comment by Xyllan** [comment]
Crashes are resolved in android/error branch.
