### ISSUE TITLE
Frontend suggestions

### ISSUE THREAD

**Issue by Xyllan** [bounswe/bounswe2015group8#229]
These are some suggestions for the web-app frontend:
 * The header can be shown at all times, even when the user has scrolled down.
 * The header should contain the currently logged user's username and their profile picture (think Facebook). This should go to the user profile page when profile page is done.
 * If the user is not logged in, the header should contain a login and a signup button.
 * Login and signup buttons are not centered
![Login and signup buttons are not centered](https://cloud.githubusercontent.com/assets/9513119/11283181/1cea4b30-8f0c-11e5-9110-c9d93edffdcd.png)
 * Signout button is not in the header
![Signout button is not in the header](https://cloud.githubusercontent.com/assets/9513119/11283199/34f8cecc-8f0c-11e5-8235-bdededbbe895.png)

**Comment by mrtysn** [comment]
Done
