### ISSUE TITLE
Backend Suggestions

### ISSUE THREAD

**Issue by Xyllan** [bounswe/bounswe2015group8#230]
## API
 * Upvote/downvote and comment API should be done ASAP.
   * Upvote post should accept member id and post id (can be merged with downvote with a boolean flag signifiying upvote or downvote). Doesn't need to return anything, but might as well return the current balance of (up - down)votes for double checking. The same goes for upvote comments.
   * Create comment should accept a comment class with fields content, owner, and post. It should return id and postDate.
 * The owner name of posts can be added to the json returned by the getHeritageById call, so that we can display them under heritages.
 * The *byId* type of calls accept ID as  integer, should probably be long values.
 * Create post and create heritage should also return postDate. In general, I'd recommend returning any fields that are generated by the backend (ie ID, post date).
 * A *getMemberById* call is necessary to have a profile page in Android, it should return the complete class with all of the posts and votes and everything (except for the password, of course).

## General
 * We need tags before we can begin semantic search and recommendation.
 * We may need to shift other members to backend if there is too much work.

**Comment by gokcantali** [comment]
Tagging system is done and available in 'tagging' branch right now,

**Comment by gokcantali** [comment]
The following items regarding API have been implemented and pushed into a branch named 'rest_api': 
  * The owner name of posts can be added to the json returned by the getHeritageById call, so that we can display them under heritages.
  * The byId type of calls accept ID as integer, should probably be long values.
  * Create post and create heritage should also return postDate. In general, I'd recommend returning any fields that are generated by the backend (ie ID, post date).
  * A getMemberById call is necessary to have a profile page in Android, it should return the complete class with all of the posts and votes and everything (except for the password, of course).

For the last item, the response is as the following:
{
  "id": 22,
  "email": "lgflgf",
  "profilePicture": "",
  "username": "hebele",
  "posts": [
    {
      "id": 27,
      "type": 0,
      "postDate": "2015-11-10 01:53:09.0",
      "lastEditedDate": "2015-11-10 01:53:08.0",
      "title": "Acaba olacak mi?",
      "content": ""
    },
    {
      "id": 6,
      "type": 0,
      "postDate": "2015-11-07 00:42:24.0",
      "lastEditedDate": "2015-11-07 00:42:23.0",
      "title": "",
      "content": "hey"
    },
    {
      "id": 31,
      "type": 0,
      "postDate": "2015-11-10 16:58:30.0",
      "lastEditedDate": "2015-11-10 16:58:30.0",
      "title": "Cikolatali",
      "content": "Cikolatali lokum"
    },
    {
      "id": 28,
      "type": 0,
      "postDate": "2015-11-10 01:53:31.0",
      "lastEditedDate": "2015-11-10 01:53:31.0",
      "title": "Acaba olacak mi?",
      "content": "Bence olacak, sen ne dusunuyorsun?"
    },
    {
      "id": 14,
      "type": 0,
      "postDate": "2015-11-07 01:56:47.0",
      "lastEditedDate": "2015-11-07 01:56:46.0",
      "title": "",
      "content": "Deneyelim bakalim"
    },
    {
      "id": 20,
      "type": 0,
      "postDate": "2015-11-08 00:48:14.0",
      "lastEditedDate": "2015-11-08 00:48:13.0",
      "title": "",
      "content": "Bakalim"
    },
    {
      "id": 4,
      "type": 0,
      "postDate": "2015-11-03 15:35:52.0",
      "lastEditedDate": "2015-11-03 15:35:51.0",
      "title": "",
      "content": "Post deneme"
    },
    {
      "id": 30,
      "type": 0,
      "postDate": "2015-11-10 14:12:59.0",
      "lastEditedDate": "2015-11-10 14:12:59.0",
      "title": "A title about lokum",
      "content": "Some content about lokum"
    },
    {
      "id": 24,
      "type": 0,
      "postDate": "2015-11-08 16:09:26.0",
      "lastEditedDate": "2015-11-08 16:09:25.0",
      "title": "Lokum",
      "content": "Here is some lokum:"
    },
    {
      "id": 25,
      "type": 0,
      "postDate": "2015-11-08 19:11:55.0",
      "lastEditedDate": "2015-11-08 19:11:55.0",
      "title": "Merhaba",
      "content": "This is a description of a lokum. Lokum is love, lokum is life."
    },
    {
      "id": 5,
      "type": 0,
      "postDate": "2015-11-06 17:38:42.0",
      "lastEditedDate": "2015-11-06 17:38:41.0",
      "title": "",
      "content": "Deneme"
    },
    {
      "id": 37,
      "type": 0,
      "postDate": "2015-11-17 04:00:51.0",
      "lastEditedDate": "2015-11-17 04:00:50.0",
      "title": "dskfsd",
      "content": "kksdfksdf"
    },
    {
      "id": 33,
      "type": 0,
      "postDate": "2015-11-10 17:26:57.0",
      "lastEditedDate": "2015-11-10 17:26:57.0",
      "title": "Balli",
      "content": "Balli lokum olur mu ya?"
    },
    {
      "id": 22,
      "type": 0,
      "postDate": "2015-11-08 16:00:13.0",
      "lastEditedDate": "2015-11-08 16:00:13.0",
      "title": "My Title",
      "content": "My content"
    },
    {
      "id": 32,
      "type": 0,
      "postDate": "2015-11-10 17:13:25.0",
      "lastEditedDate": "2015-11-10 17:13:25.0",
      "title": "My wedding",
      "content": "So cool much fun"
    },
    {
      "id": 35,
      "type": 0,
      "postDate": "2015-11-15 23:46:53.0",
      "lastEditedDate": "2015-11-15 23:46:53.0",
      "title": "Acaba?",
      "content": "Bilmemki"
    },
    {
      "id": 12,
      "type": 0,
      "postDate": "2015-11-07 01:42:51.0",
      "lastEditedDate": "2015-11-07 01:42:50.0",
      "title": "",
      "content": "heyhey"
    },
    {
      "id": 13,
      "type": 0,
      "postDate": "2015-11-07 01:47:41.0",
      "lastEditedDate": "2015-11-07 01:47:41.0",
      "title": "",
      "content": "Post"
    },
    {
      "id": 23,
      "type": 0,
      "postDate": "2015-11-08 16:04:24.0",
      "lastEditedDate": "2015-11-08 16:04:24.0",
      "title": "My title",
      "content": "My content"
    },
    {
      "id": 34,
      "type": 0,
      "postDate": "2015-11-15 20:44:31.0",
      "lastEditedDate": "2015-11-15 20:44:31.0",
      "title": "Acaba?",
      "content": "Bilmem"
    },
    {
      "id": 2,
      "type": 0,
      "postDate": "2015-11-03 13:51:36.0",
      "lastEditedDate": "2015-11-03 13:51:35.0",
      "title": "",
      "content": "Deneme"
    },
    {
      "id": 21,
      "type": 0,
      "postDate": "2015-11-08 01:59:46.0",
      "lastEditedDate": "2015-11-08 01:59:45.0",
      "title": "Benim Postum",
      "content": "Ben ne istersem onu yazarim"
    },
    {
      "id": 26,
      "type": 0,
      "postDate": "2015-11-08 21:18:03.0",
      "lastEditedDate": "2015-11-08 21:18:03.0",
      "title": "My grandfather's wedding",
      "content": "A picture from his wedding."
    },
    {
      "id": 39,
      "type": 0,
      "postDate": "2015-11-23 23:50:34.0",
      "lastEditedDate": "2015-11-23 23:50:33.0",
      "title": "nmnhmh",
      "content": "rhrhrth"
    },
    {
      "id": 1,
      "type": 0,
      "postDate": "2015-11-03 13:37:55.0",
      "lastEditedDate": "2015-11-03 13:37:54.0",
      "title": "",
      "content": "Deneme"
    },
    {
      "id": 15,
      "type": 0,
      "postDate": "2015-11-07 02:28:57.0",
      "lastEditedDate": "2015-11-07 02:28:56.0",
      "title": "",
      "content": ""
    },
    {
      "id": 3,
      "type": 0,
      "postDate": "2015-11-03 13:59:29.0",
      "lastEditedDate": "2015-11-03 13:59:28.0",
      "title": "",
      "content": "HeyHey"
    },
    {
      "id": 29,
      "type": 0,
      "postDate": "2015-11-10 14:12:21.0",
      "lastEditedDate": "2015-11-10 14:12:21.0",
      "title": "A title about lokum",
      "content": "Some content about lokum"
    }
  ],
  "comments": [
    {
      "id": 2,
      "postId": 28,
      "postDate": "2015-11-16 03:51:05.0",
      "lastEditedDate": "2015-11-16 03:51:04.0",
      "content": "heyhey"
    },
    {
      "id": 3,
      "postId": 25,
      "postDate": "2015-11-16 18:53:31.0",
      "lastEditedDate": "2015-11-16 18:53:31.0",
      "content": "This is SPARTAAA"
    },
    {
      "id": 8,
      "postId": 37,
      "postDate": "2015-11-17 04:01:01.0",
      "lastEditedDate": "2015-11-17 04:01:01.0",
      "content": "lkdfgmdfgkdf"
    },
    {
      "id": 5,
      "postId": 27,
      "postDate": "2015-11-17 03:13:50.0",
      "lastEditedDate": "2015-11-17 03:13:49.0",
      "content": "Ne dersiniz?"
    },
    {
      "id": 1,
      "postId": 25,
      "postDate": "2015-11-16 03:25:38.0",
      "lastEditedDate": "2015-11-16 03:25:37.0",
      "content": "I think this is good!"
    },
    {
      "id": 9,
      "postId": 39,
      "postDate": "2015-11-23 23:50:47.0",
      "lastEditedDate": "2015-11-23 23:50:46.0",
      "content": "what is this shit?"
    }
  ],
  "postVotes": [
    {
      "postId": 28,
      "voteType": false
    },
    {
      "postId": 25,
      "voteType": true
    }
  ],
  "commentVotes": [
    {
      "commentId": 3,
      "voteType": false
    },
    {
      "commentId": 1,
      "voteType": true
    }
  ]
}

**Comment by gokcantali** [comment]
Upvote/Downvote and Comment APIs are done and available in branch 'editpost_commentapi'.
Creating comment requires the following format:
{
    "content": "BIr seyler bir seyler",
    "ownerId": 23,
    "postId": 31
}

Voting comments requires the following format:
{
    "ownerId": 22,
    "commentId": 12,
    "voteType": false
}

Voting posts requires the following format:
{
    "ownerId": 22,
    "postId": 31,
    "voteType": true
}

You can see the responses by using the Chrome extension 'Postman'
