### ISSUE TITLE
Code Review Assignment

### ISSUE THREAD

**Issue by Xyllan** [bounswe/bounswe2015group8#299]
Please do a code review on the a03aafb7054d8ec0e0e7653287174dffb5bee12f commit until midnight today.

**Comment by bugrahan** [comment]
Code clarity:
	I think codes are written as possible as understandable. Doruk who is owner of the commit prevents to write unnecessary codes. As I see from added and deleted lines on the comment, he changed redundant part of the code. Also he preferred to use switch-case statements instead of many if-else statements which I prefer too. I think it increases readability of code.
	On the other hand, in xml files, everything is clear. He followed the convention which we defined as mobile team. As an alternative to writing color codes and string names in every xml documents, he called them from another xml file which is include all color codes and string names.
	
	Bugs:
	As far as I know and as far as I see, there is no bug in the code. We use this code for a long time and we did not face to any bug until now.
	
	Missing Features:
	This code is about a generic add button which uses at adding heritages and posts. Making button is completed but adding it to pages is missing. These insufficiencies are remark as TODOs. These TODOs are completed at next comments.
	
	Coding Convention:
	- All variable names are sufficiently enough. They point out why they used.
	- There is no problem about indentations. All of them is proper.
	- Unfortunately, there is no comment in the code.

	Documentation:
	Although the code is understandable and very readable, it needs documentation to understand complete stranger to our works. Our group did not give attention to documentation yet.

	Coverage with unit tests:
	In spite of the fact that we did not face to any bug until now, to guarantee we will not face in the future the code needs the unit tests.

	I think the code can be modified easily but it does not need to. Since the code fulfils its duty, I could not think any improvement or modification :)
	Coding style of Doruk is good. All functions and methods are separately written. It makes the code modular, readable, understandable and modifiable easily. As I mentioned above, switch-case statements make the code prettier.

	Hereby, Doruk made an excellent work even if there are some missing things such comments and documentations. But all of us did not pay enough attention these things.

**Comment by bugrahan** [comment]
I'm sorry for formal language😅 I supposed it should be like this but I thing I'm wrong🙈 Great job! :+1:

**Comment by Xyllan** [comment]
Documentation and comments are available at e61305591712599e1c78da08a9706d1622d422c1. Since this commit is only about UI, there were no unit tests available that I could implement. Android *does* have an automated UI testing module, but since that is not what this assignment asked, I did not implement that.
