### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by tugceeskili** [bounswe/bounswe2015group8#306]
Please perform a code review on my commit 12c9f10 until midnight.

**Comment by arslanbenzer** [comment]
## Review of the commit  12c9f10 ##
### *Code Clarity*
It is a well designed and organized commit. 

### *Bugs*
There is no bugs in first test. But there may be some issues in depth testing. Code works without errors.

### *Missing Features*
The pages reflect well the needs. But design may be improved a little.

### *Coding Convention*
•	Variable Names: Variable names are good but some numerical values used in code may cause some misunderstandings. Instead some predefined values may be used.

•	Indentation: Indentation is very well. It reflects the hierarchy.

•	Comments: The comments are missing. You could consider adding some comments to increase readability of the code.

### *Incomplete Code Documentation*
There is no code documentation. It can increase the effectiveness and future developement of code to add some documentation

### *Coverage with Unit Tests*
I cannot find any unit test functions. I think it will be added later but it is good to create tests on time.

### *Code Modification*
It is easy to modify the code. I can change actions and placements of elements in the code.

### *Construct Style*
Organization and hierarchy of the code are well.

### *Code Analysis Tools*
The tools suggested some minor changes but they don't affect the behaviour of the code.

Thank you for doing a careful work. It was easy to analize the code and give some reports about it.
