### ISSUE TITLE
Required APIs for profile page

### ISSUE THREAD

**Issue by arslanbenzer** [bounswe/bounswe2015group8#316]
Please implement these APIs. They are crucial for designing a profile page.
#### 1.  Follow user: ####
takes userid and followed user id as inputs, returns followed user id. followed user is added to followed users list
#### 2.  Unfollow user:  ####
takes userid and followed user id as inputs, returns unfollowed user id.unfollowed user is removed from followed users list
#### 3.  Upload profile picture. ####
Takes userid and profile picture url (string) as input and returns user.
#### 4.  Follow heritage: ####
 takes userid and followed heritage id as inputs, returns followed heritage id. followed heritage is added to followed heritages list
#### 5.  unfollow heritage: ####
takes userid and unfollowed heritage id as inputs, returns unfollowed heritage id. unfollowed heritage is removed from followed heritages list

**Comment by gokcantali** [comment]
The requested APIs are implemented and ready in the 'follow-api' branch. You can deploy the code there and test them.

Follow User API (/api/follow)
{
    "followerId": 23,
    "followeeId": 22
}
returns 22

Unfollow User API (/api/unfollow)
{
    "followerId": 23,
    "followeeId": 22
}
returns 22

Follow Heritage API (/api/followHeritage)
{
    "followerId": 22,
    "heritageId": 3
}
returns 3

Unfollow Heritage API (/api/unfollowHeritage)
{
    "followerId": 22,
    "heritageId": 3
}
returns 3

Profile Picture Upload API (/api/uploadProfilePicture)
{
    "userId": 22,
    "profilePicture": "www.profilepictures.com/image/123456789"
}
returns the whole member object in json format
