### ISSUE TITLE
Media attachment feedback needed

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2015group8#350]
I am able to attach media, however it kind of messes up the picture. When I attach media, I would like to see something (like the name of the file, or thumbnail of the image) so I can tell there is an image.

**Comment by gokcantali** [comment]
This enhancement actually was in our schedule for a while, but since we focused on other major bugs/issues, we kind of postponed it. We can show the name of the uploaded file next to the attachement  image.
@berksalmanoglu can you look at this improvement right now?

**Comment by gokcantali** [comment]
With the new deployment, the file name is displayed right next to the attachment image after the user attaches a media. 
If there is still a problem, please let us know asap.
