### ISSUE TITLE
Adding multiple images to posts

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2015group8#351]
I would like to be able to add more than one image. But, I guess that is out of question now. 

It is more important to be able to put images within posts.

**Comment by gokcantali** [comment]
Actually, it is now possible to add multiple media files to a post :)
However, the user can still only add one image whilst creating the post. But after creating it, the user can choose to edit her/his post and add another media using the 'Add Media' button. This approach also fixes the issue #348 as we removed media editing from the edit form which is associated with 'Post' button.
