### ISSUE TITLE
Text of post does not preserve paragraphs and spacing 

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2015group8#352]
I logged in as uskudarli

I created a heritage: Coffee

I created a post: The memory of a cup of coffee lasts for 40 years -- the folk story 
under Coffee heritage

I entered a post that had some paragraphs. When I posted it, all spaces were gone. 

My post was:

So, the coffee story...

It seems there was a man named Üsküdarlı Bilge who sold and made coffee. He was actually a coffee seller, but people of all walks of life would come there to have coffee, visit, and get some advice at times. His coffee was known with the bitter taste. I guess you could call it full flavored.

One day a infidel came to his shop. It was full of people. Among all the Turks there was a Greek Captain man  in the corner smoking  a water pipe.

The janissary announced that he was offering coffee to all the wise, kind, insightful persons, with the exception of the infidel in the corner. The captain sighed and went on smoking his pipe.

The wise owner of the shop made coffee as asked. After serving the coffee  he made a couple of more cups and went to sit and have some coffee with the captain.

The janissary exclaimed, "Hey! Didn't I say except the infidel?"

The wise man said this is my offering not yours. He went on visiting with the Captain for a good long time. The Captain was so impressed that he entered this event in his journal.

Years go by... 40 years to be exact. There are Greek uprisings in Samos island. The Wise man, being included in the janissaries is stationed in Samos and is captured during the uprising. The captured slaves are sold to gain some income and most are killed. An old man pays a good price for our wise coffee seller puts him in his service. He takes him to a secluded area. The Captain remembers the coffee seller, but the wise man does not remember the captain.

The captain says: Oh wise man, the coffee you have offered me  has created a bond that has lasted for 40 years. Even if you have forgotten, I have not. You are a free man. However, if you wish I can take you to your homeland safely.

--

The post can be seen at:

http://ec2-54-187-115-133.us-west-2.compute.amazonaws.com:8080/WeStory/show_posts/28

**Comment by uskudarli** [comment]
I thing the <pre> tag might be able to help. CSS also has options for handling white spaces.

**Comment by gokcantali** [comment]
You are actually right. If we give the style "white-space: pre" to the html elements, it can display the whitespaces without a problem. Thank you so much for the feedback and suggestion. We will fix the issue with the next deployment.

**Comment by uskudarli** [comment]
:+1:

**Comment by gokcantali** [comment]
The bug is fixed with the new deployment. You can check it and let us know the result.
