### ISSUE TITLE
Location specification for regions and paths

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2015group8#354]
No idea how to specify locations that are region:
    City
    Country
    Continent
Path
     Roads (route 66, Walls, walk between Kuzey and Guney campus, etc.)
Buildings
     Maybe this is okay with Geolocation...

**Comment by gokcantali** [comment]
Our Google Map API has been improved with the latest deployment. Now, the user can specify the location detail level. After you choose a value from the dropdown list, you can select a geolocation by clicking on the map, and its location information will be automatically written into the input field below. 
And if you are not satisfied with the result, you can always edit it by typing the exact place information you want to give.

**Comment by gokcantali** [comment]
Please let us know if something is not clear enough.
